
# RPMsg / OpenAMP
CONFIG_IPM=y 
#abilita il sistema di messagistica tra processori
CONFIG_OPENAMP=y 
#carica la libreria OpenAMP
CONFIG_RPMSG_SERVICE=y 
#attiva lo strato semplificato Service sopra OPenAMP
CONFIG_IPC_SERVICE=y
CONFIG_RPMSG_SERVICE_MODE_MASTER=y 
# definisce che Zephyr è il  master

#DAL MAIN.C
CONFIG_PRINTK=y 
#PRINTK
CONFIG_CBPRINTF_FP_SUPPORT=y  
#per vedere i float nel PRINTF
# Numeri casuali (sys_rand32_get)
CONFIG_ENTROPY_GENERATOR=y
CONFIG_TEST_RANDOM_GENERATOR=y
CONFIG_TIMER_RANDOM_GENERATOR=y

#x86
CONFIG_X86_COMMON_PAGE_TABLE=n
CONFIG_SRAM_REGION_PERMISSIONS=n

#GESTIONE MEMORIA
CONFIG_HEAP_MEM_POOL_SIZE=16384 
#riserva memoria dinamica RAM 
CONFIG_MAIN_STACK_SIZE=4096 
#aumenta la dimensione dello stack del thread principale
CONFIG_X86_MMU=n
#la dimensione non è allineata ai blocchi di 4kB riciesti dalla MMU (memory management unit) di x86